import { Subject, Lesson } from '@/types'

export const SUBJECTS: Subject[] = [
  {
    id: 'math',
    name: 'Math',
    icon: '🔢',
    color: '#FF6B6B',
    description: 'Numbers, counting, and shapes',
    order: 1,
  },
  {
    id: 'english',
    name: 'English',
    icon: '📖',
    color: '#4D96FF',
    description: 'Alphabet, phonics, and first words',
    order: 2,
  },
  {
    id: 'science',
    name: 'Science',
    icon: '🔬',
    color: '#6BCB77',
    description: 'Animals, plants, and nature',
    order: 3,
  },
]

export const LESSONS: Lesson[] = [
  // Math Lessons
  {
    id: 'math-1',
    subjectId: 'math',
    title: 'Counting 1–5',
    description: 'Learn to count from 1 to 5',
    type: 'quiz',
    order: 1,
    difficulty: 1,
    isActive: true,
    content: {
      instructions: 'Count the items shown and select the correct number.',
      items: [
        {
          id: '1',
          question: 'How many apples are there?',
          options: ['1', '2', '3', '4'],
          answer: 0,
          imageUrl: '🍎',
        },
        {
          id: '2',
          question: 'How many bananas are there?',
          options: ['1', '2', '3', '4'],
          answer: 1,
          imageUrl: '🍌🍌',
        },
        {
          id: '3',
          question: 'How many stars do you see?',
          options: ['2', '3', '4', '5'],
          answer: 1,
          imageUrl: '⭐⭐⭐',
        },
        {
          id: '4',
          question: 'How many flowers are there?',
          options: ['2', '3', '4', '5'],
          answer: 2,
          imageUrl: '🌸🌸🌸🌸',
        },
        {
          id: '5',
          question: 'How many balls are there?',
          options: ['3', '4', '5', '6'],
          answer: 1,
          imageUrl: '⚽⚽⚽⚽',
        },
      ],
    },
  },
  {
    id: 'math-2',
    subjectId: 'math',
    title: 'Counting 6–10',
    description: 'Learn to count from 6 to 10',
    type: 'quiz',
    order: 2,
    difficulty: 1,
    isActive: true,
    content: {
      instructions: 'Count the items shown and select the correct number.',
      items: [
        {
          id: '1',
          question: 'How many oranges are there?',
          options: ['5', '6', '7', '8'],
          answer: 1,
          imageUrl: '🍊🍊🍊🍊🍊🍊',
        },
        {
          id: '2',
          question: 'How many strawberries are there?',
          options: ['6', '7', '8', '9'],
          answer: 2,
          imageUrl: '🍓🍓🍓🍓🍓🍓🍓🍓',
        },
        {
          id: '3',
          question: 'How many hearts do you see?',
          options: ['7', '8', '9', '10'],
          answer: 1,
          imageUrl: '❤️❤️❤️❤️❤️❤️❤️❤️',
        },
        {
          id: '4',
          question: 'How many bells are there?',
          options: ['8', '9', '10', '7'],
          answer: 2,
          imageUrl: '🔔🔔🔔🔔🔔🔔🔔🔔🔔🔔',
        },
        {
          id: '5',
          question: 'How many suns are there?',
          options: ['7', '8', '9', '6'],
          answer: 2,
          imageUrl: '☀️☀️☀️☀️☀️☀️☀️☀️☀️',
        },
      ],
    },
  },
  {
    id: 'math-3',
    subjectId: 'math',
    title: 'Basic Shapes',
    description: 'Learn circles, squares, triangles, and rectangles',
    type: 'quiz',
    order: 3,
    difficulty: 1,
    isActive: true,
    content: {
      instructions: 'Identify the correct shape name.',
      items: [
        {
          id: '1',
          question: 'What shape is this? 🔴',
          options: ['Triangle', 'Circle', 'Square', 'Rectangle'],
          answer: 1,
          imageUrl: '🔴',
        },
        {
          id: '2',
          question: 'What shape is this? 🟩',
          options: ['Circle', 'Rectangle', 'Square', 'Triangle'],
          answer: 2,
          imageUrl: '🟩',
        },
        {
          id: '3',
          question: 'What shape is this? 🔺',
          options: ['Rectangle', 'Circle', 'Triangle', 'Square'],
          answer: 2,
          imageUrl: '🔺',
        },
        {
          id: '4',
          question: 'What shape is this? 🟥',
          options: ['Triangle', 'Square', 'Rectangle', 'Circle'],
          answer: 2,
          imageUrl: '🟥',
        },
        {
          id: '5',
          question: 'What shape has 4 equal sides? �',
          options: ['Circle', 'Triangle', 'Square', 'Rectangle'],
          answer: 2,
          imageUrl: '�',
        },
      ],
    },
  },
  {
    id: 'math-4',
    subjectId: 'math',
    title: 'Simple Addition',
    description: 'Add numbers 1-5',
    type: 'quiz',
    order: 4,
    difficulty: 2,
    isActive: true,
    content: {
      instructions: 'Solve the addition problems.',
      items: [
        {
          id: '1',
          question: '1 + 1 = ?',
          options: ['1', '2', '3', '4'],
          answer: 1,
          imageUrl: '1️⃣ ➕ 1️⃣',
        },
        {
          id: '2',
          question: '2 + 1 = ?',
          options: ['2', '3', '4', '5'],
          answer: 1,
          imageUrl: '2️⃣ ➕ 1️⃣',
        },
        {
          id: '3',
          question: '3 + 2 = ?',
          options: ['4', '5', '6', '3'],
          answer: 1,
          imageUrl: '3️⃣ ➕ 2️⃣',
        },
        {
          id: '4',
          question: '2 + 2 = ?',
          options: ['2', '3', '4', '5'],
          answer: 2,
          imageUrl: '2️⃣ ➕ 2️⃣',
        },
        {
          id: '5',
          question: '4 + 1 = ?',
          options: ['3', '4', '5', '6'],
          answer: 2,
          imageUrl: '4️⃣ ➕ 1️⃣',
        },
      ],
    },
  },
  {
    id: 'math-5',
    subjectId: 'math',
    title: 'Patterns',
    description: 'Identify and continue patterns',
    type: 'quiz',
    order: 5,
    difficulty: 2,
    isActive: true,
    content: {
      instructions: 'What comes next in the pattern?',
      items: [
        {
          id: '1',
          question: '🔴 🔵 🔴 🔵 🔴 — What comes next?',
          options: ['�', '🔴', '�', '🟡'],
          answer: 2,
          imageUrl: '🔴🔵🔴🔵🔴',
        },
        {
          id: '2',
          question: '🟩 🟡 🟩 🟡 🟩 — What comes next?',
          options: ['�', '�', '�', '🔵'],
          answer: 2,
          imageUrl: '🟩🟡🟩🟡🟩',
        },
        {
          id: '3',
          question: '⭐ 🌙 ⭐ 🌙 ⭐ — What comes next?',
          options: ['⭐', '☀️', '🌟', '🌙'],
          answer: 3,
          imageUrl: '⭐🌙⭐🌙⭐',
        },
        {
          id: '4',
          question: '🍎 🍊 🍎 🍊 🍎 — What comes next?',
          options: ['�', '�', '�', '�'],
          answer: 1,
          imageUrl: '🍎🍊🍎🍊🍎',
        },
        {
          id: '5',
          question: '🐶 🐱 🐶 🐱 🐶 — What comes next?',
          options: ['�', '�', '�', '🐹'],
          answer: 2,
          imageUrl: '🐶🐱🐶🐱🐶',
        },
      ],
    },
  },

  // English Lessons
  {
    id: 'english-1',
    subjectId: 'english',
    title: 'Alphabet A–M',
    description: 'Learn the first half of the alphabet',
    type: 'quiz',
    order: 1,
    difficulty: 1,
    isActive: true,
    content: {
      instructions: 'Which letter comes after the given letter?',
      items: [
        {
          id: '1',
          question: 'What letter comes after A?',
          options: ['B', 'C', 'D', 'E'],
          answer: 0,
          imageUrl: '🔤 A → ?',
        },
        {
          id: '2',
          question: 'What letter comes after C?',
          options: ['D', 'E', 'F', 'G'],
          answer: 0,
          imageUrl: '🔤 C → ?',
        },
        {
          id: '3',
          question: 'What letter comes after E?',
          options: ['F', 'G', 'H', 'I'],
          answer: 0,
          imageUrl: '🔤 E → ?',
        },
        {
          id: '4',
          question: 'What letter comes after G?',
          options: ['H', 'I', 'J', 'K'],
          answer: 0,
          imageUrl: '🔤 G → ?',
        },
        {
          id: '5',
          question: 'What letter comes after J?',
          options: ['K', 'L', 'M', 'N'],
          answer: 0,
          imageUrl: '🔤 J → ?',
        },
      ],
    },
  },
  {
    id: 'english-2',
    subjectId: 'english',
    title: 'Alphabet N–Z',
    description: 'Learn the second half of the alphabet',
    type: 'quiz',
    order: 2,
    difficulty: 1,
    isActive: true,
    content: {
      instructions: 'Which letter comes after the given letter?',
      items: [
        {
          id: '1',
          question: 'What letter comes after N?',
          options: ['O', 'P', 'Q', 'R'],
          answer: 0,
          imageUrl: '🔤 N → ?',
        },
        {
          id: '2',
          question: 'What letter comes after Q?',
          options: ['R', 'S', 'T', 'U'],
          answer: 0,
          imageUrl: '🔤 Q → ?',
        },
        {
          id: '3',
          question: 'What letter comes after S?',
          options: ['T', 'U', 'V', 'W'],
          answer: 0,
          imageUrl: '🔤 S → ?',
        },
        {
          id: '4',
          question: 'What letter comes after U?',
          options: ['V', 'W', 'X', 'Y'],
          answer: 0,
          imageUrl: '🔤 U → ?',
        },
        {
          id: '5',
          question: 'What letter comes after W?',
          options: ['X', 'Y', 'Z', 'A'],
          answer: 0,
          imageUrl: '🔤 W → ?',
        },
      ],
    },
  },
  {
    id: 'english-3',
    subjectId: 'english',
    title: 'Phonics Basics',
    description: 'Learn basic sounds',
    type: 'quiz',
    order: 3,
    difficulty: 1,
    isActive: true,
    content: {
      instructions: 'What sound does this letter make?',
      items: [
        {
          id: '1',
          question: 'What sound does "A" make?',
          options: ['aaa (like apple)', 'bbb', 'ccc', 'ddd'],
          answer: 0,
          imageUrl: '🍎',
        },
        {
          id: '2',
          question: 'What sound does "B" make?',
          options: ['aaa', 'bbb (like ball)', 'ccc', 'ddd'],
          answer: 1,
          imageUrl: '⚽',
        },
        {
          id: '3',
          question: 'What sound does "C" make?',
          options: ['aaa', 'bbb', 'ccc (like cat)', 'ddd'],
          answer: 2,
          imageUrl: '🐱',
        },
        {
          id: '4',
          question: 'What sound does "D" make?',
          options: ['aaa', 'bbb', 'ccc', 'ddd (like dog)'],
          answer: 3,
          imageUrl: '🐶',
        },
        {
          id: '5',
          question: 'What sound does "E" make?',
          options: ['eee (like egg)', 'fff', 'ggg', 'hhh'],
          answer: 0,
          imageUrl: '🥚',
        },
      ],
    },
  },
  {
    id: 'english-4',
    subjectId: 'english',
    title: 'First Words',
    description: 'Learn simple 3-letter words',
    type: 'quiz',
    order: 4,
    difficulty: 2,
    isActive: true,
    content: {
      instructions: 'What is this word?',
      items: [
        {
          id: '1',
          question: 'C-A-T spells?',
          options: ['cat', 'bat', 'rat', 'hat'],
          answer: 0,
          imageUrl: '🐱',
        },
        {
          id: '2',
          question: 'D-O-G spells?',
          options: ['dig', 'dog', 'dot', 'dug'],
          answer: 1,
          imageUrl: '🐶',
        },
        {
          id: '3',
          question: 'B-A-T spells?',
          options: ['cat', 'mat', 'bat', 'sat'],
          answer: 2,
          imageUrl: '🦇',
        },
        {
          id: '4',
          question: 'H-A-T spells?',
          options: ['cat', 'bat', 'rat', 'hat'],
          answer: 3,
          imageUrl: '🎩',
        },
        {
          id: '5',
          question: 'S-U-N spells?',
          options: ['run', 'fun', 'sun', 'bun'],
          answer: 2,
          imageUrl: '☀️',
        },
      ],
    },
  },
  {
    id: 'english-5',
    subjectId: 'english',
    title: 'Rhyming Words',
    description: 'Learn words that rhyme together',
    type: 'quiz',
    order: 5,
    difficulty: 2,
    isActive: true,
    content: {
      instructions: 'Which word rhymes with the given word?',
      items: [
        {
          id: '1',
          question: 'Which word rhymes with "cat"?',
          options: ['bat', 'dog', 'run', 'sun'],
          answer: 0,
          imageUrl: '🐱 & 🦇',
        },
        {
          id: '2',
          question: 'Which word rhymes with "dog"?',
          options: ['cat', 'fog', 'bat', 'rat'],
          answer: 1,
          imageUrl: '🐶 & 🌫️',
        },
        {
          id: '3',
          question: 'Which word rhymes with "run"?',
          options: ['sit', 'fun', 'walk', 'jump'],
          answer: 1,
          imageUrl: '🏃 & 😄',
        },
        {
          id: '4',
          question: 'Which word rhymes with "sun"?',
          options: ['moon', 'fun', 'star', 'night'],
          answer: 1,
          imageUrl: '☀️ & 😄',
        },
        {
          id: '5',
          question: 'Which word rhymes with "bee"?',
          options: ['apple', 'tree', 'dog', 'cat'],
          answer: 1,
          imageUrl: '🐝 & 🌳',
        },
      ],
    },
  },

  // Science Lessons
  {
    id: 'science-1',
    subjectId: 'science',
    title: 'Animals Around Us',
    description: 'Learn about common animals',
    type: 'quiz',
    order: 1,
    difficulty: 1,
    isActive: true,
    content: {
      instructions: 'What is this animal?',
      items: [
        {
          id: '1',
          question: 'What is this animal? 🐶',
          options: ['dog', 'cat', 'rabbit', 'mouse'],
          answer: 0,
          imageUrl: '🐶',
        },
        {
          id: '2',
          question: 'What is this animal? 🐱',
          options: ['dog', 'cat', 'rabbit', 'mouse'],
          answer: 1,
          imageUrl: '🐱',
        },
        {
          id: '3',
          question: 'What is this animal? 🐰',
          options: ['dog', 'cat', 'rabbit', 'mouse'],
          answer: 2,
          imageUrl: '🐰',
        },
        {
          id: '4',
          question: 'What is this animal? 🦁',
          options: ['tiger', 'lion', 'bear', 'wolf'],
          answer: 1,
          imageUrl: '🦁',
        },
        {
          id: '5',
          question: 'What is this animal? 🐘',
          options: ['rhino', 'giraffe', 'elephant', 'hippo'],
          answer: 2,
          imageUrl: '🐘',
        },
      ],
    },
  },
  {
    id: 'science-2',
    subjectId: 'science',
    title: 'Plants & Trees',
    description: 'Learn about plants and trees',
    type: 'quiz',
    order: 2,
    difficulty: 1,
    isActive: true,
    content: {
      instructions: 'What is this plant or tree?',
      items: [
        {
          id: '1',
          question: 'What is this? 🌳',
          options: ['flower', 'tree', 'grass', 'bush'],
          answer: 1,
          imageUrl: '🌳',
        },
        {
          id: '2',
          question: 'What is this? 🌸',
          options: ['flower', 'tree', 'grass', 'bush'],
          answer: 0,
          imageUrl: '🌸',
        },
        {
          id: '3',
          question: 'What is this? 🌻',
          options: ['flower', 'tree', 'grass', 'bush'],
          answer: 0,
          imageUrl: '🌻',
        },
        {
          id: '4',
          question: 'What is this? 🍎 from a tree?',
          options: ['flower', 'fruit', 'leaf', 'seed'],
          answer: 1,
          imageUrl: '🍎',
        },
        {
          id: '5',
          question: 'What is this? 🌻 grows in?',
          options: ['water', 'soil', 'air', 'rock'],
          answer: 1,
          imageUrl: '🌻',
        },
      ],
    },
  },
  {
    id: 'science-3',
    subjectId: 'science',
    title: 'Weather',
    description: 'Learn about different weather',
    type: 'quiz',
    order: 3,
    difficulty: 1,
    isActive: true,
    content: {
      instructions: 'What is this weather?',
      items: [
        {
          id: '1',
          question: 'What is this weather? ☀️',
          options: ['sunny', 'rainy', 'snowy', 'windy'],
          answer: 0,
          imageUrl: '☀️',
        },
        {
          id: '2',
          question: 'What is this weather? 🌧️',
          options: ['sunny', 'rainy', 'snowy', 'windy'],
          answer: 1,
          imageUrl: '🌧️',
        },
        {
          id: '3',
          question: 'What is this weather? ❄️',
          options: ['sunny', 'rainy', 'snowy', 'windy'],
          answer: 2,
          imageUrl: '❄️',
        },
        {
          id: '4',
          question: 'What is this weather? ⛅',
          options: ['sunny', 'cloudy', 'snowy', 'windy'],
          answer: 1,
          imageUrl: '⛅',
        },
        {
          id: '5',
          question: 'What is this weather? 🌈',
          options: ['sunny', 'rainy', 'rainbow', 'stormy'],
          answer: 2,
          imageUrl: '🌈',
        },
      ],
    },
  },
  {
    id: 'science-4',
    subjectId: 'science',
    title: 'My Body',
    description: 'Learn about body parts',
    type: 'quiz',
    order: 4,
    difficulty: 1,
    isActive: true,
    content: {
      instructions: 'What body part is this?',
      items: [
        {
          id: '1',
          question: 'What is this body part? 👁️',
          options: ['nose', 'eye', 'ear', 'mouth'],
          answer: 1,
          imageUrl: '👁️',
        },
        {
          id: '2',
          question: 'What is this body part? 👃',
          options: ['nose', 'eye', 'ear', 'mouth'],
          answer: 0,
          imageUrl: '👃',
        },
        {
          id: '3',
          question: 'What is this body part? 👂',
          options: ['nose', 'eye', 'ear', 'mouth'],
          answer: 2,
          imageUrl: '👂',
        },
        {
          id: '4',
          question: 'What is this body part? ✋',
          options: ['foot', 'hand', 'arm', 'leg'],
          answer: 1,
          imageUrl: '✋',
        },
        {
          id: '5',
          question: 'What is this body part? 🦵',
          options: ['foot', 'hand', 'arm', 'leg'],
          answer: 3,
          imageUrl: '🦵',
        },
      ],
    },
  },
  {
    id: 'science-5',
    subjectId: 'science',
    title: 'Colors in Nature',
    description: 'Learn colors from nature',
    type: 'quiz',
    order: 5,
    difficulty: 2,
    isActive: true,
    content: {
      instructions: 'What color is this?',
      items: [
        {
          id: '1',
          question: 'What color is a 🍎?',
          options: ['yellow', 'red', 'green', 'blue'],
          answer: 1,
          imageUrl: '🍎',
        },
        {
          id: '2',
          question: 'What color is the 🌳?',
          options: ['brown', 'green', 'blue', 'yellow'],
          answer: 1,
          imageUrl: '🌳',
        },
        {
          id: '3',
          question: 'What color is the ☀️?',
          options: ['red', 'orange', 'yellow', 'blue'],
          answer: 2,
          imageUrl: '☀️',
        },
        {
          id: '4',
          question: 'What color is the 🌊?',
          options: ['green', 'red', 'yellow', 'blue'],
          answer: 3,
          imageUrl: '🌊',
        },
        {
          id: '5',
          question: 'What color is a 🍋?',
          options: ['orange', 'green', 'yellow', 'red'],
          answer: 2,
          imageUrl: '🍋',
        },
      ],
    },
  },
]
